### ISSUE TITLE
clone.sh requires special permissions

### ISSUE THREAD

**Issue by Caerbannog** [RangeNetworks/dev#16]
Running clone.sh when you have no github account or no special permission results in the following command being executed:

    $ git clone git@github.com:RangeNetworks/asterisk.git
    Cloning into 'asterisk'...
    Permission denied (publickey).
    fatal: Could not read from remote repository.
    Please make sure you have the correct access rights
    and the repository exists.

The solution could be change the script to clone over HTTP. Alternatively the permissions of the repositories could be changed.

**Comment by iedemam** [comment]
A patch provided by @ttsou to clone.sh reminded this is still a pain for people. I've swapped all submodule references to use HTTPS and applied his patch to the dev script. Things should be clone-able without need for SSH keys now.
