### ISSUE TITLE
Error Installing on Ubuntu 14.04

### ISSUE THREAD

**Issue by junaid124** [RangeNetworks/dev#20]
Not working on Ubuntu 14.04.
deb files of all component are made in build directory but when i tried to install errors comes out 
sudo dpkg -i BUILD-2014-04-27--19-53-08/*.deb
(Reading database ... 247888 files and directories currently installed.)
Preparing to unpack .../liba53_0.1_amd64.deb ...
Unpacking liba53 (0.1) over (0.1) ...
Preparing to unpack .../libcoredumper1_1.2.1-1_amd64.deb ...
Unpacking libcoredumper1 (1.2.1-1) over (1.2.1-1) ...
Preparing to unpack .../libcoredumper-dev_1.2.1-1_amd64.deb ...
Unpacking libcoredumper-dev (1.2.1-1) over (1.2.1-1) ...
Preparing to unpack .../openbts_4.1_amd64.deb ...
Unpacking openbts (4.1) over (4.1) ...
Preparing to unpack .../range-asterisk_11.7.0.4_amd64.deb ...
Unpacking range-asterisk (11.7.0.4) over (11.7.0.4) ...
Preparing to unpack .../range-asterisk-config_4.1_amd64.deb ...
Unpacking range-asterisk-config (4.1) over (4.1) ...
Selecting previously unselected package range-configs.
Preparing to unpack .../range-configs_4.1_amd64.deb ...
Unpacking range-configs (4.1) ...
Preparing to unpack .../range-libsqliteodbc_0.995-2_amd64.deb ...
SQLITE has been deleted (if it existed at all) because its usage count became zero
SQLITE3 has been deleted (if it existed at all) because its usage count became zero
Unpacking range-libsqliteodbc (0.995-2) over (0.995-2) ...
Preparing to unpack .../range-libzmq_3.2.2.3_amd64.deb ...
Unpacking range-libzmq (3.2.2.3) over (3.2.2.3) ...
Preparing to unpack .../sipauthserve_4.1_amd64.deb ...
Unpacking sipauthserve (4.1) over (4.1) ...
Preparing to unpack .../smqueue_4.1_amd64.deb ...
Unpacking smqueue (4.1) over (4.1) ...
Setting up liba53 (0.1) ...
Setting up libcoredumper1 (1.2.1-1) ...
Setting up libcoredumper-dev (1.2.1-1) ...
Setting up range-asterisk-config (4.1) ...
dpkg: dependency problems prevent configuration of range-configs:
 range-configs depends on libapache2-mod-authnz-external; however:
  Package libapache2-mod-authnz-external is not installed.
 range-configs depends on pwauth; however:
  Package pwauth is not installed.
 range-configs depends on ntp; however:
  Package ntp is not installed.
 range-configs depends on bind9; however:
  Package bind9 is not installed.

dpkg: error processing package range-configs (--install):
 dependency problems - leaving unconfigured
Setting up range-libsqliteodbc (0.995-2) ...
odbcinst: Driver installed. Usage count increased to 1. 
    Target directory is /etc
odbcinst: Driver installed. Usage count increased to 1. 
    Target directory is /etc
Setting up range-libzmq (3.2.2.3) ...
Setting up sipauthserve (4.1) ...
Setting up smqueue (4.1) ...
Setting up openbts (4.1) ...
chown: invalid user: ‘openbts:openbts’
chown: invalid user: ‘openbts:openbts’
chown: invalid user: ‘openbts:openbts’
chown: invalid user: ‘openbts:openbts’
Setting up range-asterisk (11.7.0.4) ...
Processing triggers for libc-bin (2.19-0ubuntu6) ...
Processing triggers for man-db (2.6.7.1-1) ...
Processing triggers for ureadahead (0.100.0-16) ...
ureadahead will be reprofiled on next reboot
Errors were encountered while processing:
 range-configs

**Comment by codenoid** [comment]
i do manually install .deb, and re run that command, and fine
