### ISSUE TITLE
Can't open lib '/usr/lib/odbc/libsqlite3odbc.so' : file not found

### ISSUE THREAD

**Issue by Ari100tell** [RangeNetworks/dev#32]
I cann`t make call in the OpenBTS network and in the OpenBTS(Asterisk) logs I get next message
---Can't open lib '/usr/lib/odbc/libsqlite3odbc.so' : file not found

When I want to send SMS in my network I get the next messages on my phone:
---Can`t send your SMS to ******: Phone not registered here.:

How I can fix this errors?

**Comment by iedemam** [comment]
fixed in master
