### ISSUE TITLE
./OpenBTSCLI says “is openbts running”

### ISSUE THREAD

**Issue by samwbs** [RangeNetworks/dev#34]
I sudo start sipauthserve/smqueue/openbts/asterisk.
It's all normal.
But when i ./OpenBTSCLI ，something wrong happend.
I try to re-install，the same problem appeared.
I think i have started openbts ，why is openbts not running?

**Comment by RuxandraO** [comment]
You need to have the device connected when you run /OpenBTS7OpenBTSCLI. Is it?

**Comment by maliksaad84** [comment]
i am encountering the same problem. Please help me out even the device is configured and uhd_find_devices work . But getting same issue connection refusing when running sudo openbts/openbtscli
