### ISSUE TITLE
Install OpenBTS on Ubuntu 16.04; is it feasible?

### ISSUE THREAD

**Issue by RuxandraO** [RangeNetworks/dev#35]
Hello,

Has anybody managed to install OpenBTS on Ubuntu 16.04? 
Or at least is it known that it does not work?

(I keep trying, but each time I fix an error I got a new one...)

Thanks!

**Comment by iedemam** [comment]
Hi, thanks for the report.

I took a look at this and you're right, there were a lot of little things to take care of. I've committed changes to each of the packages which should get them working as well as the dev/build.sh script so the proper dependencies are installed.

My environment was a fresh install of Ubuntu Desktop 16.04 AMD64.

Please give it a try and let me know how it goes. I think this will get your environment up to date:

````
$ cd to/your/dev/clone
$ git pull
$ ./pull.sh
$ ./build.sh YOURRADIO
````

Regards,
-Michael

**Comment by RuxandraO** [comment]
Hi!

Thanks for you quick reply but sorry, I've already downgraded to 14.04. 

This seems to work much better, but still I have a problem when I want to access the CLI:

[Connecting to 127.0.0.1:49300...
connect stream socket: Connection refused
Is OpenBTS running?]

Any solution to that?

Thanks!

**Comment by iedemam** [comment]
Glad to see it builds on 14.04 as well apparently. I can only recommend you try on 16.04.

Did you see if OpenBTS is running as the message asks? What do the logs say? What happens if you try to run OpenBTS manually?

**Comment by RuxandraO** [comment]
Sorry my mistake! It is ok now, I just had to wait some more time until the device was up.

Thanks!

**Comment by tom-2015** [comment]
I get error on Ubuntu 16.04 32bit with uhd-host 3.9.4-5

```
# Add here commands to clean up after the build process.
/usr/bin/make distclean
make[1]: Entering directory '/home/pi/dev/libcoredumper/coredumper-1.2.1'
make[1]: *** No rule to make target 'distclean'.  Stop.
make[1]: Leaving directory '/home/pi/dev/libcoredumper/coredumper-1.2.1'
debian/rules:55: recipe for target 'clean' failed
make: [clean] Error 2 (ignored)
cp -f /usr/share/misc/config.sub config.sub
cp -f /usr/share/misc/config.guess config.guess
dh_clean 
dh_clean: Compatibility levels before 5 are no longer supported (level 4 requested)
debian/rules:55: recipe for target 'clean' failed
make: *** [clean] Error 25
dpkg-buildpackage: error: debian/rules clean gave error exit status 2
ERROR: command failed!
# ERROR: command failed!
```

Any ideas on fixing this?

**Comment by bhushan-bmsce** [comment]
I could create the builds and install openbts on 16.04LTS. However, when I start the services, Ubuntu 16.04 tries to use Upstart which is deprecated in all versions of Ubuntu from 15.04 onwards and hence fails. Ubuntu 16.04 uses systemd for launch of services and hence the problem. 
Derrick says on https://www.maketecheasier.com/re-enable-upstart-ubuntu/ that there is a way to swap systemd with Upstart and swap back. However, it doesn't seem to work and 16.04 doesn't boot if you make this change (at least on my system). However, I recovered.  Any further pointers? Welcome. Thanks

**Comment by nadiia-kotelnikova** [comment]
I have built OpenBTS on fresh Ubuntu 16.04.
@bhushan-bmsce if You still did not fix that issue, You can find scripts for ```systemd``` in my repository https://github.com/nadiia-kotelnikova/openbts_systemd_scripts.

**Comment by dvolvox** [comment]
@tom-2015 bypass it by going to the libcoredumper folder and: ./configure && make && make install

**Comment by RuxandraO** [comment]
The problem is that Ubuntu 16.04 comes with UHD 3.9.2-1, but it seems that Ettus B200mini (apparently B200 in general) needs at most 3.7.3 to work fine. So, even if OpenBTS is apparently working, for example the TMSI table remains always empty at an attempt to connect a phone. Any solution to this? Anyone had the same problem? Thank you!

**Comment by tom-2015** [comment]
It needs 3.9.0 which is lower than 3.9.2 so normally it should work?
Are you able to connect your phone? Try to use the osmo-trx as transceiver that worked for me (there is a bug in the OpenBTS transceiver with UHD 3.9.0).
More: https://github.com/EttusResearch/uhd/issues/65

**Comment by Keskebeu** [comment]
Osmo-trx is not installing on my 16.04lts it comes up with an error when i run make. The issue comes up in transceiver52M directory of uhd. 

Although I have built a uhd transceiver from yatebts transceiver starts but is still does not come with tchf and sach. I am using uhd 3.9.X.

**Comment by ff1016** [comment]
I am trying to install openbts following the steps mentioned [here](http://openbts.org/w/index.php?title=BuildInstallRun). I am using ubuntu 16.04 LTS and ettus USRP N210. Every time I am running the command (./build.sh N210) I am getting an error. Below is the list of errors that I have found. 

By selecting (./switchto.sh master) branch and after running the command (./build.sh N210) Error log shows the following:

2018-05-20T10:59:59\" -MT UHDDevice.lo -MD -MP -MF .deps/UHDDevice.Tpo -c UHDDevice.cpp  -fPIC -DPIC -o .libs/UHDDevice.o
UHDDevice.cpp:29:29: fatal error: uhd/utils/msg.hpp: No such file or directory
compilation terminated.
Makefile:665: recipe for target 'UHDDevice.lo' failed
make[3]: *** [UHDDevice.lo] Error 1
make[3]: Leaving directory '/home/wslopenbts/dev/openbts/Transceiver52M'
Makefile:572: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/wslopenbts/dev/openbts'
Makefile:503: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/wslopenbts/dev/openbts'
debian/rules:74: recipe for target 'install-arch' failed
make: *** [install-arch] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
# ERROR: command failed!

While I was searching, I have found someone had the same issue and he used (./switchto.sh 5.0) to fix the issue. I also tried to do so but got this error. 

wslopenbts@wslopenbts-Inspiron-560:~/dev$ ./build.sh N210
# checking for a supported radio type
# - found
# checking for a compatible build host
# - fully supported host detected: Ubuntu 16.04
#
# adding additional repo tools
# - done

# checking build dependencies
# - done

# make a home for this build
mkdir -p BUILDS/2018-05-20--13-23-20
# libcoredumper - building Debian package and installing as dependency
cd libcoredumper
./build.sh
wget http://google-coredumper.googlecode.com/files/coredumper-1.2.1.tar.gz
--2018-05-20 13:23:20--  http://google-coredumper.googlecode.com/files/coredumper-1.2.1.tar.gz
Resolving google-coredumper.googlecode.com (google-coredumper.googlecode.com)... 209.85.232.82, 2607:f8b0:400d:c08::52
Connecting to google-coredumper.googlecode.com (google-coredumper.googlecode.com)|209.85.232.82|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-05-20 13:23:20 ERROR 404: Not Found.

ERROR: command failed!
# ERROR: command failed!

Then I have tried different way by selecting (./switchto.sh 4.0) branch and after running the command (./build.sh N210) Error log shows the following:

END failed--call queue aborted at /usr/bin/dh_installdirs line 243.
debian/rules:69: recipe for target 'install-arch' failed
make: *** [install-arch] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
# ERROR: command failed!

By selecting (./switchto.sh v4.0.0) branch and after running the command (./build.sh N210) Error log shows the following:

END failed--call queue aborted at /usr/bin/dh_installdirs line 243.
debian/rules:69: recipe for target 'install-arch' failed
make: *** [install-arch] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
# ERROR: command failed!

Can anyone please help me to fix the issue.

Thanks in advance.

**Comment by Keskebeu** [comment]
git submodule init
git submodule update

Than do ./switchto.sh master

./build N210

**Comment by ff1016** [comment]
Still I am getting the following error. 

2018-05-24T22:19:55\" -MT UHDDevice.lo -MD -MP -MF .deps/UHDDevice.Tpo -c UHDDevice.cpp  -fPIC -DPIC -o .libs/UHDDevice.o
UHDDevice.cpp:29:29: fatal error: uhd/utils/msg.hpp: No such file or directory
compilation terminated.
Makefile:665: recipe for target 'UHDDevice.lo' failed
make[3]: *** [UHDDevice.lo] Error 1
make[3]: Leaving directory '/home/wslopenbts/dev/openbts/Transceiver52M'
Makefile:572: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/wslopenbts/dev/openbts'
Makefile:503: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/wslopenbts/dev/openbts'
debian/rules:74: recipe for target 'install-arch' failed
make: *** [install-arch] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
# ERROR: command failed!

**Comment by nadiia-kotelnikova** [comment]
@ff1016  did You install UHD driver?

**Comment by ff1016** [comment]
Yes, I did. Okay, till now what I have done, I am summarizing here. 
I have installed UHD driver following the instructions mentioned [here ](https://kb.ettus.com/Building_and_Installing_the_USRP_Open-Source_Toolchain_(UHD_and_GNU_Radio)_on_Linux)and the installed UHD version is 3.11.0.  Then, I have tried to verify the Operation of the USRP Using UHD and GNURadio following the instruction mentioned [here](https://kb.ettus.com/Verifying_the_Operation_of_the_USRP_Using_UHD_and_GNU_Radio). I have got some error messages in two commands. Running this (**./tx_samples_from_file --freq 915e6 --rate 5e6 --gain 10 usrp_samples.dat**) command, showed the following error.

_wslopenbts@wslopenbts-Inspiron-560:/usr/local/lib/uhd/examples$ ./tx_samples_from_file --freq 915e6 --rate 5e6 --gain 10 usrp_samples.dat
Creating the usrp device with: ...
[INFO] [UHD] linux; GNU C++ version 5.4.0 20160609; Boost_105800; UHD_3.11.0.HEAD-0-g13c32cef
[INFO] [USRP2] Opening a USRP2/N-Series device...
[INFO] [USRP2] Current recv frame size: 1472 bytes
[INFO] [USRP2] Current send frame size: 1472 bytes
Using Device: Single USRP:
  Device: USRP2 / N-Series Device
  Mboard 0: N210r4
  RX Channel: 0
    RX DSP: 0
    RX Dboard: A
    RX Subdev: WBXv4 RX+GDB
  TX Channel: 0
    TX DSP: 0
    TX Dboard: A
    TX Subdev: WBXv4 TX+GDB
Setting TX Rate: 5.000000 Msps...
Actual TX Rate: 5.000000 Msps...
Setting TX Freq: 915.000000 MHz...
Actual TX Freq: 915.000000 MHz...
Setting TX Gain: 10.000000 dB...
Actual TX Gain: 10.000000 dB...
Checking TX: LO: unlocked ...
Error: AssertionError: lo_locked.to_bool()
  in int _main(int, char**)
  at /home/wslopenbts/workarea-uhd/uhd/host/examples/tx_samples_from_file.cpp:161_

The output with error of this (**./tx_waveforms --freq 915e6 --rate 5e6 --gain 0**) command is given below:

_wslopenbts@wslopenbts-Inspiron-560:/usr/local/lib/uhd/examples$ ./tx_waveforms --freq 915e6 --rate 5e6 --gain 0
Creating the usrp device with: ...
[INFO] [UHD] linux; GNU C++ version 5.4.0 20160609; Boost_105800; UHD_3.11.0.HEAD-0-g13c32cef
[INFO] [USRP2] Opening a USRP2/N-Series device...
[INFO] [USRP2] Current recv frame size: 1472 bytes
[INFO] [USRP2] Current send frame size: 1472 bytes
Using Device: Single USRP:
  Device: USRP2 / N-Series Device
  Mboard 0: N210r4
  RX Channel: 0
    RX DSP: 0
    RX Dboard: A
    RX Subdev: WBXv4 RX+GDB
  TX Channel: 0
    TX DSP: 0
    TX Dboard: A
    TX Subdev: WBXv4 TX+GDB
Setting TX Rate: 5.000000 Msps...
Actual TX Rate: 5.000000 Msps...
Setting TX Freq: 915.000000 MHz...
Actual TX Freq: 915.000000 MHz...
Setting TX Gain: 0.000000 dB...
Actual TX Gain: 0.000000 dB...
Setting device timestamp to 0...
Checking TX: LO: unlocked ...
Error: AssertionError: lo_locked.to_bool()
  in int _main(int, char**)
  at /home/wslopenbts/workarea-uhd/uhd/host/examples/tx_waveforms.cpp:213_

Can you please inform me, Do I need to reinstall UHD driver again, as I did this several times?

Thanks in advance
Farah

**Comment by nadiia-kotelnikova** [comment]
@ff1016  Unfortunately, I don't know the reason of your errors. But for me, installation goes without errors if I do not install UHD driver manually before OpenBTS installation and do not add Ettus repository. For the Ettus manufacture build.sh script automatically installs UHD driver from the Ubuntu repository:
```
installIfMissing libuhd-dev
installIfMissing libuhd003
installIfMissing uhd-host
```

I would suggest installing from the beginning on fresh OS.
Here what I am doing:
```
sudo apt install git ntp ntpdate bind9 resolvconf
git clone https://github.com/RangeNetworks/dev.git
cd dev/
./clone.sh
./build.sh N210
cd BUILDS/20XX-XX-XX--XX-XX-XX/
sudo dpkg -i *.deb

```

**Comment by ff1016** [comment]
After downgrading the UHD version (UHD 3.10.3.0), I am able to install OpenBTS. Previously I was using the UHD 3.11.0.0.
Thanks a lot for your suggestions.

**Comment by victoraugusto7** [comment]
Someone could help me with this : how did you downgrade the UHD version to 3.10.3.0? What command must I have to write?
I am getting the same error : UHDDevice.cpp:29:29: fatal error: uhd/utils/msg.hpp: No such file or directory
Thanks

**Comment by Keskebeu** [comment]
Make sure you go to uhd host and run make uninstall make clean. And than
install 3.10.3. Or simply sudo apt-get install uhd-host.

It will work with range Network.

**Comment by victoraugusto7** [comment]
Thanks Keskebeu! 
I already fixed the issue based in these steps:
 https://kb.ettus.com/Building_and_Installing_the_USRP_Open-Source_Toolchain_(UHD_and_GNU_Radio)_on_Linux

**Comment by bloodandwolf** [comment]
UHDDevice.cpp:29:29: fatal error: uhd/utils/msg.hpp: 没有那个文件或目录
compilation terminated.
Makefile:665: recipe for target 'UHDDevice.lo' failed
make[3]: *** [UHDDevice.lo] Error 1
make[3]: Leaving directory '/root/dev/openbts/Transceiver52M'
Makefile:572: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/root/dev/openbts'
Makefile:503: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/root/dev/openbts'
debian/rules:74: recipe for target 'install-arch' failed
make: *** [install-arch] Error 2
dpkg-buildpackage: 错误: debian/rules binary 提供错误退出状态 2
# ERROR: command failed!

**Comment by Keskebeu** [comment]
You won't be able to build it. Do it manually.

**Comment by oladimeji-abdul** [comment]
i've been trying to compile with /.build.sh but i'm getting 
unmet dependencies: liba53
and i already make install liba53 in its directory but same error keeps popping up. i really need someone to help me with this because it is my final year project and it is due for submission in 4 days

**Comment by Keskebeu** [comment]
Don't use ./build.sh compile manually every one of them.
Make sure you install liba53 from range networks

**Comment by oladimeji-abdul** [comment]
dear keskebeu, how do i compile manually pls.
best regards

**Comment by oladimeji-abdul** [comment]
how do i compile manually please

**Comment by oladimeji-abdul** [comment]
i have successsfuy compiled the dependencies manually, now i am recieving this error
collect2: error: ld returned 1 exit status
Makefile:606: recipe for target 'transceiver' failed
make[3]: *** [transceiver] Error 1
make[3]: Leaving directory '/home/tcsbts19/dev/openbts/Transceiver52M'
Makefile:572: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/tcsbts19/dev/openbts'
Makefile:503: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/tcsbts19/dev/openbts'
debian/rules:74: recipe for target 'install-arch' failed
make: *** [install-arch] Error 2
dpkg-buildpackage: error: debian/rules binary gave error exit status 2
# ERROR: command failed!

**Comment by Keskebeu** [comment]
Add the -lpthread flag to your make.

**Comment by Keskebeu** [comment]
Add the -lpthread Flagg to your make files manually in the transceiver file
in uhd file Transceiver52M

**Comment by shuidixu** [comment]
Hello all,

is there any updated guide that helps installing the software?
Should I use Ubuntu 12.04, (as stated in the wiki), or should I switch to 16.04?

Thank you sirs

**Comment by Keskebeu** [comment]
16.04
