### ISSUE TITLE
recipe for target 'install-arch' failed

### ISSUE THREAD

**Issue by Techi1188** [RangeNetworks/dev#39]
Hello,
  First off I am trying to get openBTS installed on an I7-4700MQ, Ubuntu 16.04, 64-bit system, please let me know if I need to add any other machine specifics.

Next, I keep received this error when trying to build for the N210 (please see attached screen shot)

![error](https://cloud.githubusercontent.com/assets/22626280/19093792/affca900-8a5a-11e6-8f18-c9241720c10d.JPG)

I tried ./pull.sh and it says everything is up to date

I know other people have successfully used openBTS with ubuntu 16.04 before so I don't understand why it won't build. Please let me know what I can try, Thank you.

**Comment by iedemam** [comment]
Are you using the master branch? Run this to use that branch:

`$ ./switchto.sh master`

**Comment by Techi1188** [comment]
Hi Iedemam,
  I did that and it got past the arch issue, but now I get this error:

# subscriberRegistry - building Debian package
cd subscriberRegistry
./common.source: line 21: cd: subscriberRegistry: No such file or directory
# ERROR: command failed!

I tried doing another git pull, then ./pull.sh but that did not help.
