### ISSUE TITLE
build.sh needs radio-type option to support different radio hardware

### ISSUE THREAD

**Issue by iedemam** [RangeNetworks/dev#4]
The build script needs user input on what type of radio is being used. This way, the specific configure flags can be set for the openbts package and appropriate links set in apps.

**Comment by tnbt27** [comment]
I tried ./build.sh command.

ERROR : radio type must be specified
# usage: ./build.sh.sh radio-type (component-name)
# valid radio types are: SDR1, USRP1, B100, B110, B200, B210, N200, N210
# (optional) valid component names are: libcoredumper, liba53, subscriberRegistry, smqueue, openbts, asterisk, asterisk-config, system-config

**Comment by iedemam** [comment]
already implemented
