### ISSUE TITLE
openbts make fail

### ISSUE THREAD

**Issue by Peterthegreat** [RangeNetworks/dev#47]
Hello, I am trying to build openbts 5.0 on a debian based distro. The build fails when "make all" is sent for openbts package (everything else builds fine)
Looks like g++ cannot convert ‘os’ type in some files.  (gcc version (4:6.3.0-4), 
Linux kali 4.9.0-kali3-amd64 # 1 SMP Debian 4.9.18-1kali1 (2017-04-04) x86_64 GNU/Linux)

Here is a partial log.

...
In file included from /usr/include/c++/6/istream:39:0,
                 from /usr/include/c++/6/sstream:38,
                 from ../CommonLibs/Logger.h:41,
                 from L3StateMachine.h:31,
                 from L3StateMachine.cpp:19:
om ../CommonLibs/Logger.h:41,
                 from L3StateMachine.h:31,
                 from L3StateMachine.cpp:19:
/usr/include/c++/6/ostream:497:5: note: candidate: template<class _CharT, class _Traits> std::basic_ostream<_CharT, _Traits>& std::operator<<(std::basic_ostream<_CharT, _Traits>&, _CharT)
     operator<<(basic_ostream<_CharT, _Traits>& __out, _CharT __c)
     ^~~~~~~~
/usr/include/c++/6/ostream:497:5: note:   template argument deduction/substitution failed:
L3StateMachine.cpp:92:22: note:   deduced conflicting types for parameter ‘_CharT’ (‘char’ and ‘std::__cxx11::basic_ostringstream<char>’)
   Log(level).get() <<os <<" Unexpected"<<LOGHEX(state);
                      ^~
In file included from /usr/include/c++/6/bits/ios_base.h:46:0,
                 from /usr/include/c++/6/ios:42,
                 from /usr/include/c++/6/istream:38,
                 from /usr/include/c++/6/sstream:38,
                 from ../CommonLibs/Logger.h:41,
                 from L3StateMachine.h:31,
                 from L3StateMachine.cpp:19:
/usr/include/c++/6/system_error:209:5: note: candidate: template<class _CharT, class _Traits> std::basic_ostream<_CharT, _Traits>& std::operator<<(std::basic_ostream<_CharT, _Traits>&, const std::error_code&)
     operator<<(basic_ostream<_CharT, _Traits>& __os, const error_code& __e)
     ^~~~~~~~
/usr/include/c++/6/system_error:209:5: note:   template argument deduction/substitution failed:
L3StateMachine.cpp:92:22: note:   cannot convert ‘os’ (type ‘std::ostringstream {aka std::__cxx11::basic_ostringstream<char>}’) to type ‘const std::error_code&’
   Log(level).get() <<os <<" Unexpected"<<LOGHEX(state);
                      ^~
In file included from /usr/include/c++/6/string:52:0,
                 from /usr/include/c++/6/stdexcept:39,
                 from /usr/include/c++/6/array:39,
                 from /usr/include/c++/6/tuple:39,
                 from /usr/include/c++/6/bits/stl_map.h:63,
                 from /usr/include/c++/6/map:61,
                 from L3StateMachine.h:29,
                 from L3StateMachine.cpp:19:
/usr/include/c++/6/bits/basic_string.h:5340:5: note: candidate: template<class _CharT, class _Traits, class _Alloc> std::basic_ostream<_CharT, _Traits>& std::operator<<(std::basic_ostream<_CharT, _Traits>&, const std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&)
     operator<<(basic_ostream<_CharT, _Traits>& __os,
     ^~~~~~~~
/usr/include/c++/6/bits/basic_string.h:5340:5: note:   template argument deduction/substitution failed:
L3StateMachine.cpp:92:22: note:   ‘std::ostringstream {aka std::__cxx11::basic_ostringstream<char>}’ is not derived from ‘const std::__cxx11::basic_string<_CharT, _Traits, _Alloc>’
   Log(level).get() <<os <<" Unexpected"<<LOGHEX(state);
                      ^~
Makefile:568: recipe for target 'L3StateMachine.lo' failed
make[2]: *** [L3StateMachine.lo] Error 1
make[2]: Leaving directory '/root/Desktop/PwN/dev/openbts/Control'
Makefile:572: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/Desktop/PwN/dev/openbts'
Makefile:503: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by dmeyerholt** [comment]
Using gcc 5 fixes that problem

**Comment by Peterthegreat** [comment]
Thanks for your reply, eventually I compiled from Ubuntu

**Comment by briansalehi** [comment]
> Thanks for your reply, eventually I compiled from Ubuntu

by any chance, do you remember how you did it? previous comment is said to be using gcc 5, but I'm using *gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0* and I don't thinking downgrading my gcc would be a good idea! any suggestions?

**Comment by Peterthegreat** [comment]
sorry, it was quite a while ago. I don't remember the solution. Try a gcc reinstall first, then the gcc5. best of luck!
