### ISSUE TITLE
Need some help!. I'm having problem on creating dial plan to make call.

### ISSUE THREAD

**Issue by yondonjamts0** [RangeNetworks/dev#49]
I cloned and built this version of openbts and my mobile phone could find and connected to the network correctly. But I have no idea on creating dial plan in _extensions.conf_ or _sip.conf_. Also the server sent back the imsi code to my phone and I need to register that imsi in my openbts. Need some help on it.

**Comment by Peterthegreat** [comment]
first you need to register your imsi and define a phone number for each one.
$ cd openbts/dev/NodeManager
$ ./nmcli.py sipauthserve subscribers create "some_name" imsi IMSI************* \phone_number
then you reconect to the network and sms/phone should work (check if all modules-openbts, sipauthserve, asterisk, smqueue- are started)

**Comment by yondonjamts0** [comment]
@Peterthegreat thank you for your help, I'm sure that it's gonna work so, but in my case, I didn't burn a new sim card but the old sim cards which been being used in my country, so when I reconnect to my network, I'm getting a new imsi for each connections. 
Can I hold my imsi in the case not using new sim card? Thank you :)

**Comment by Peterthegreat** [comment]
I didn't used new sims cards for my connections (I did not write any info on them -such as Ki number-), and each imei had the same imsi on every connection to the network
