### ISSUE TITLE
Need some help on building openbts ASAP. 

### ISSUE THREAD

**Issue by yondonjamts0** [RangeNetworks/dev#50]
I'm trying to build openbts and make the whole things correctly until $ ./build <radio-type> . But when I do this, I'm taking the error which is below.  /home/vanchinbal/dev/openbts/Transceiver52M/UHDDevice.cpp:667: undefined reference to `uhd::msg::register_handler(void (* const&)(uhd::msg::type_t, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&))'
collect2: error: ld returned 1 exit status
Makefile:606: recipe for target 'transceiver' failed
make[3]: *** [transceiver] Error 1
make[3]: Leaving directory '/home/vanchinbal/dev/openbts/Transceiver52M'
Makefile:572: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/vanchinbal/dev/openbts'
Makefile:503: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/vanchinbal/dev/openbts'
debian/rules:74: recipe for target 'install-arch' failed
make: *** [install-arch] Error 2
dpkg-buildpackage: error: debian/rules binary gave error exit status 2
# ERROR: command failed!

How to solve this?

**Comment by iedemam** [comment]
There was an API change in UHD recently. What version of UHD are you using?

**Comment by yondonjamts0** [comment]
Ohh well, I think its version 3.11.0 and isn't this version fit to the openbts? If so, which version can be? :)

**Comment by yondonjamts0** [comment]
I found some solution.

1. Remove your UHD from your computer
2. Reinstall UHD from old tree (use download as zip! Because if you cloned with some link it will automatically downloading latest version)
3. Remove you gcc compiler (sudo apt remove gcc)
4. install old version of GCC compiler. I used that one 
  4.1 sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  4.2 sudo apt update
  4.3 sudo apt install g++-4.9
  4.4 sudo apt install build-essential
5. Recompile your old version of UHD and install
6. Recompile your OpenBTS   <  ./build $RADIO_TYPE  >
Sincere thanks, Mr.Michael @iedemam

**Comment by oladimeji-abdul** [comment]
how do i recompile the old version of uhd and install pls

**Comment by yondonjamts0** [comment]
>
> Clone it from master and checkout branch as UHD-3.9.LTS and pull from the
> current branch.

Or you could just download with
> https://github.com/EttusResearch/uhd/archive/UHD-3.9.LTS.zip

**Comment by oladimeji-abdul** [comment]
here is what i compiled. hope i am on the right track
root@tcsbts19-oneTwo-M3700:~/uhd# git checkout release_003_010_000_000

**Comment by oladimeji-abdul** [comment]
thank you
